<#
    Install Windows updates, one round per reboot.

    Disabled in steps.json by default: the answer file generated by
    schneegans.de pauses Windows Update, and updates make a first build much
    slower. Set "enabled": true in steps.json when you do want it.

    This step exits 3011, which means "reboot and run me again", so several
    rounds of updates can complete without hand holding.
#>
. "$PSScriptRoot\_lib.ps1"

Write-Info 'Lifting the Windows Update pause set by the answer file.'
Unregister-ScheduledTask -TaskName 'PauseWindowsUpdate' -Confirm:$false -ErrorAction SilentlyContinue
$settings = 'HKLM:\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings'
if (Test-Path -LiteralPath $settings) {
    foreach ($name in @('PauseFeatureUpdatesStartTime', 'PauseFeatureUpdatesEndTime',
                        'PauseQualityUpdatesStartTime', 'PauseQualityUpdatesEndTime',
                        'PauseUpdatesExpiryTime')) {
        Remove-ItemProperty -LiteralPath $settings -Name $name -Force -ErrorAction SilentlyContinue
    }
}

if (-not (Get-Module -ListAvailable -Name 'PSWindowsUpdate')) {
    Write-Info 'Installing the PSWindowsUpdate module.'
    Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force | Out-Null
    Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
    Install-Module -Name 'PSWindowsUpdate' -Force -Scope AllUsers
}

Import-Module PSWindowsUpdate

$available = Get-WindowsUpdate -MicrosoftUpdate -IgnoreReboot
if (-not $available) {
    Write-Info 'No updates are available.'
    exit 0
}

Write-Info ("Installing {0} update(s)." -f @($available).Count)
Install-WindowsUpdate -MicrosoftUpdate -AcceptAll -IgnoreReboot | Out-Host

# Come back after a reboot and look for the next round.
Write-Info 'Updates installed; rebooting and checking again.'
exit 3011
